### ISSUE TITLE
OpenAI

### ISSUE THREAD

**Issue by dataf3l** [dereklstinson/gpufans#1]
this is unrelated to anything, but it looks like GPT3 expects you to have written a word2vec golabg thing.

did this exist?
Or was it halucinated by the AI?

I asked the ai:

"Create a tutorial about how to use word2vec to write a simple recommendation engine in python including code samples"

it came up with this:

...
more input:
Word2vec and golang

```
This tutorial will show you how to use the word2vec algorithm to write a simple recommendation engine in golang. We will first need to install the go-word2vec library, which can be done using the go get command:

go get github.com/dereklstinson/goword2vec

Once go-word2vec is installed, we can import it and create a word2vec model:

import "github.com/dereklstinson/goword2vec" model := goword2vec.NewModel() err := model.Load("/path/to/model.bin") if err != nil { panic(err) }

Now that we have our model, we can start using it to recommend items to users. For this tutorial, we will be using a dataset of movie ratings. Each row in the dataset represents a user's rating for a particular movie.
```

so basically I'm just here to say that the gpt3 AI seems to have it's faith in you that it will be you who will bring word2vec to golang.
I am puzzled.

**Comment by dataf3l** [comment]
So congrats? I guess? I don't know what this means, honestly.
so maybe thank you, like a lot.
keep publishing open source code?

**Comment by dereklstinson** [comment]
I've never used GPT3. I guess it recognized me as one of the few people using Go with machine learning. Then made up the rest. It sure has a wild imagination.

**Comment by dataf3l** [comment]
Just keep being awesome :)
